apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kubernetes-lan
  namespace: istio-system
spec:
  secretName: wildcard-cert
  duration: 2160h
  renewBefore: 360h
  commonName: "*.kubernetes.lan"
  dnsNames:
    - "*.kubernetes.lan"
    - "kubernetes.lan"
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
