#cloud-config
hostname: ${hostname}

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - open-iscsi
  - cri-dockerd
  - docker.io
  - nfs-kernel-server

groups:
  - docker

users:
  - name: ubuntu
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    groups: docker

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable containerd
  - systemctl start containerd
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl enable iscsid
  - systemctl start iscsid
  - systemctl enable nfs-kernel-server.service
  - systemctl start nfs-kernel-server.service
  - sudo systemctl stop multipathd
  - sudo systemctl disable multipathd
  - modprobe dm_crypt

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: true

fs_setup:
  - device: /dev/sdb1
    filesystem: ext4
    label: longhorn-data
    overwrite: true

mounts:
  - [ /dev/sdb1, /var/lib/longhorn, "ext4", "defaults,nofail,x-systemd.requires=cloud-init.service", "0", "2" ]
