apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-applications
  namespace: argo
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  generators:
    - list:
        elements:
          - name: longhorn
            valueFiles: env/production/longhorn-defaults.yml
            namespace: longhorn-system
            environment: production
  template:
    metadata:
      name: '{{name}}-{{environment}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/carlos-eduardo-dev/big-data'
        targetRevision: HEAD
        path: 'charts/{{name}}'
        helm:
          valueFiles:
            - '{{valueFiles}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true