apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: business-applications
  namespace: argo
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  generators:
    - list:
        elements:
          - name: minio-operator
            values: /charts/minio-operator/env/production/minio-operator-defaults.yml
            syncWave: '1'
            namespace: minio-operator
            environment: production
  template:
    metadata:
      name: '{{name}}-{{environment}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/carlos-eduardo-dev/big-data'
        targetRevision: HEAD
        path: 'charts/{{name}}'
        helm:
          valueFiles:
            - '{{values}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true