apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/carlos-eduardo-dev/big-data'
    path: 'big-data/apps'
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true