apiVersion: v1
kind: Secret
metadata:
  name: awscreds
  namespace: nessie
type: Opaque
stringData:
#  local minio access key :)
  aws_access_key_id: "Hcbo4HK4iFLoAuqt8p6d"
  aws_secret_access_key: "15DL8GPUX287c3sheASkglXVkj0zxyupityh3LmM"
---
apiVersion: v1
kind: Secret
metadata:
  name: default-creds
  namespace: nessie
type: Opaque
stringData:
  defaultAccessKeyId: "Hcbo4HK4iFLoAuqt8p6d"
  defaultSecretAccessKey: "15DL8GPUX287c3sheASkglXVkj0zxyupityh3LmM"